### ISSUE TITLE
chroma subsampling per region

### ISSUE THREAD

**Issue by couleurm** [derrod/obs-roi-ui#2]
Hello, I like to record in YUV444 to keep my GUI sharp on Minecraft
![image](https://github.com/derrod/obs-roi-ui/assets/82747632/cfb8182b-a517-43be-93ec-39b62ade0b4c)

Would some kind of region e.g. like this, to only record in YUV444 on certain regions and YUV420 on the rest of them?

![AP3_purp](https://github.com/derrod/obs-roi-ui/assets/82747632/69bcd9ad-dbb9-44f5-8d74-78de1ffa0b35)

(Ignore the square at the middle I use this to mask out RSMB-style motion blur smearing)

**Comment by derrod** [comment]
That's not possible.
