### ISSUE TITLE
Can't find Encoder Region in the "Tools" tab

### ISSUE THREAD

**Issue by ValentinVmr** [derrod/obs-roi-ui#4]
Hello there !

Even if I installed manually or via the installer this plugin, there isn't the "Encoder Region of Interest Editor" button above the "Tools" tab.
Here is a screenshot (in French)

![image](https://github.com/derrod/obs-roi-ui/assets/43049119/89664605-b466-4c6c-b0a3-068da9889df1)

Thanks in advance !

**Comment by Bombi-fm** [comment]
@ValentinVmr I updated the version to the latest and it showed up for me

**Comment by ValentinVmr** [comment]
@Bombi-fm After the update, the button showed up. Thank you 🙏🙏
