### ISSUE TITLE
ROI not showing in OBS UI

### ISSUE THREAD

**Issue by essi2** [derrod/obs-roi-ui#8]
ROI does not show up in the latest TEB version v27 UI

I've reinstalled and double checked the files are located where they should be.

![image](https://github.com/derrod/obs-roi-ui/assets/30266031/cabed33d-8a21-4ffb-93b5-9c22c062d214)
![image](https://github.com/derrod/obs-roi-ui/assets/30266031/292bd918-0437-4229-b2ab-4e6365ea234e)

**Comment by derrod** [comment]
Due to the ffmpeg update it doesn't work right now

**Comment by jonnyawsom3** [comment]
Just spent a while scratching my head wondering where it went. Here's hoping it's fixed upstream for the next OBS update

**Comment by derrod** [comment]
I hope to release an update within the next week or so to restore compatibility wtih 30.2

**Comment by derrod** [comment]
Fixed in https://github.com/derrod/obs-roi-ui/releases/tag/1.1.1
